spring:
  datasource:
    url: jdbc:mysql://${storage.database.core-db.url}
    username: ${storage.database.core-db.username}
    password: ${storage.database.core-db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 5
    connection-timeout: 2000
    keepalive-time: 0
    validation-timeout: 5000
    max-lifetime: 600000
    pool-name: core-db-pool
    data-source-properties:
      socketTimeout: 3000
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  jackson:
    mapper:
      # true 설정하면 Enum 변환 시 대소문자를 구분 안함.
      accept-case-insensitive-enums: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v1/api-docs